#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OMC_CONFIG_DIR="${OMC_WRAPPER_CONFIG_DIR:-$HOME/.claude-omc}"
OMC_STATE_DIR="${OMC_WRAPPER_STATE_DIR:-$OMC_CONFIG_DIR/state}"
OMC_MARKETPLACE_REPO="https://github.com/Yeachan-Heo/oh-my-claudecode"
GIT_IGNORE_SOURCE="$REPO_ROOT/osx/config/.config/git/ignore"
GIT_IGNORE_TARGET="$HOME/.config/git/ignore"
WRAPPER_SOURCE="$REPO_ROOT/universal/omc-wrapper.sh"
WRAPPER_TARGET_LOCAL="$HOME/.local/bin/omc"
NORMAL_CLAUDE_SETTINGS="$HOME/.claude/settings.json"
ISOLATED_CLAUDE_SETTINGS="$OMC_CONFIG_DIR/settings.json"
CLAUDE_MCP_CONFIG="$HOME/.claude.json"
OMC_MCP_REGISTRY="$HOME/.omc/mcp-registry.json"
OMC_MCP_REGISTRY_STATE="$HOME/.omc/state/mcp-registry-state.json"
CODEX_CONFIG="$HOME/.codex/config.toml"
LEGACY_GEMINI_MCP_NAME="gemini-image-generation"

log() {
  printf '%s\n' "$*"
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    log "Missing required command: $1"
    exit 1
  fi
}

ensure_dirs() {
  mkdir -p "$HOME/.config/git" "$HOME/.local/bin" "$OMC_CONFIG_DIR" "$OMC_STATE_DIR"
}

mirror_macos_claude_auth() {
  if [ "$(uname -s)" != "Darwin" ] || ! command -v security >/dev/null 2>&1; then
    return
  fi

  local default_service
  local target_service
  local config_hash
  local credentials

  default_service="Claude Code-credentials"
  config_hash="$(printf '%s' "$OMC_CONFIG_DIR" | shasum -a 256 | awk '{print substr($1, 1, 8)}')"
  target_service="Claude Code-credentials-$config_hash"

  if security find-generic-password -a "$USER" -s "$target_service" >/dev/null 2>&1; then
    log "Claude auth already mirrored for isolated macOS profile: $target_service"
    return
  fi

  if ! credentials="$(security find-generic-password -w -a "$USER" -s "$default_service" 2>/dev/null)"; then
    log "No default Claude login found to mirror into isolated macOS profile"
    return
  fi

  security add-generic-password -U -a "$USER" -s "$target_service" -w "$credentials" >/dev/null
  log "Mirrored Claude login into isolated macOS keychain profile: $target_service"
}

install_git_ignore() {
  cp "$GIT_IGNORE_SOURCE" "$GIT_IGNORE_TARGET"
  git config --global core.excludesfile "$GIT_IGNORE_TARGET"
  log "Installed global git ignore: $GIT_IGNORE_TARGET"
}

install_wrapper() {
  local npm_prefix
  local wrapper_target_global

  chmod +x "$WRAPPER_SOURCE"

  ln -snf "$WRAPPER_SOURCE" "$WRAPPER_TARGET_LOCAL"
  log "Linked omc wrapper: $WRAPPER_TARGET_LOCAL -> $WRAPPER_SOURCE"

  npm_prefix="$(npm prefix -g)"
  wrapper_target_global="$npm_prefix/bin/omc"
  ln -snf "$WRAPPER_SOURCE" "$wrapper_target_global"
  log "Linked active global omc shim: $wrapper_target_global -> $WRAPPER_SOURCE"
}

install_omc_cli() {
  npm install -g oh-my-claude-sisyphus@latest
  local npm_prefix
  npm_prefix="$(npm prefix -g)"
  if [ ! -x "$npm_prefix/bin/omc" ]; then
    log "Real OMC CLI missing after npm install: $npm_prefix/bin/omc"
    exit 1
  fi
  log "Installed OMC CLI: $npm_prefix/bin/omc"
}

ensure_marketplace() {
  if CLAUDE_CONFIG_DIR="$OMC_CONFIG_DIR" claude plugins marketplace list 2>/dev/null | grep -q 'omc'; then
    log "Marketplace already configured in isolated Claude profile: omc"
    return
  fi

  CLAUDE_CONFIG_DIR="$OMC_CONFIG_DIR" claude plugins marketplace add "$OMC_MARKETPLACE_REPO" >/dev/null
  log "Added Claude marketplace to isolated OMC profile: omc"
}

ensure_plugin() {
  if CLAUDE_CONFIG_DIR="$OMC_CONFIG_DIR" claude plugins list 2>/dev/null | grep -q 'oh-my-claudecode@omc'; then
    log "Plugin already installed in isolated Claude profile: oh-my-claudecode@omc"
    return
  fi

  CLAUDE_CONFIG_DIR="$OMC_CONFIG_DIR" claude plugins install oh-my-claudecode@omc --scope user >/dev/null
  log "Installed Claude plugin in isolated OMC profile: oh-my-claudecode@omc"
}

run_omc_setup() {
  OMC_WRAPPER_CONFIG_DIR="$OMC_CONFIG_DIR" \
  OMC_WRAPPER_STATE_DIR="$OMC_STATE_DIR" \
  "$WRAPPER_TARGET_LOCAL" setup --quiet
  log "Ran isolated OMC setup in: $OMC_CONFIG_DIR"
}

merge_safe_base_settings() {
  if [ ! -f "$ISOLATED_CLAUDE_SETTINGS" ]; then
    log "Isolated Claude settings missing: $ISOLATED_CLAUDE_SETTINGS"
    exit 1
  fi

  if ! command -v jq >/dev/null 2>&1; then
    log "jq not found; leaving isolated settings as generated by OMC"
    return
  fi

  local merged_settings
  merged_settings="$(mktemp)"

  if [ -f "$NORMAL_CLAUDE_SETTINGS" ]; then
    jq -s '
      .[0] as $isolated
      | .[1] as $normal
      | $normal
      | .enabledPlugins = (($normal.enabledPlugins // {}) + ($isolated.enabledPlugins // {}))
      | .env = (($normal.env // {}) + ($isolated.env // {}) + {"CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS": "1"})
      | .extraKnownMarketplaces = (($normal.extraKnownMarketplaces // {}) + ($isolated.extraKnownMarketplaces // {}))
      | .hooks = ($isolated.hooks // ($normal.hooks // {}))
      | .statusLine = ($isolated.statusLine // ($normal.statusLine // null))
    ' "$ISOLATED_CLAUDE_SETTINGS" "$NORMAL_CLAUDE_SETTINGS" > "$merged_settings"
    log "Merged safe base Claude settings into isolated OMC profile"
  else
    jq '
      .env = ((.env // {}) + {"CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS": "1"})
    ' "$ISOLATED_CLAUDE_SETTINGS" > "$merged_settings"
    log "Enabled native Claude teams in isolated OMC profile"
  fi

  mv "$merged_settings" "$ISOLATED_CLAUDE_SETTINGS"
}

validate_settings() {
  if command -v jq >/dev/null 2>&1; then
    jq empty "$ISOLATED_CLAUDE_SETTINGS" >/dev/null
  fi
  log "Validated isolated OMC settings: $ISOLATED_CLAUDE_SETTINGS"
}

remove_legacy_gemini_image_generation() {
  local tmp

  if command -v jq >/dev/null 2>&1; then
    if [ -f "$CLAUDE_MCP_CONFIG" ]; then
      tmp="$(mktemp)"
      jq --arg name "$LEGACY_GEMINI_MCP_NAME" '
        del(.mcpServers[$name])
        | (.. | objects | select(has("disabledMcpServers")) | .disabledMcpServers) |= map(select(. != $name))
        | del(.. | objects | select(.disabledMcpServers? == []) | .disabledMcpServers)
        | if (.mcpServers // null) == {} then del(.mcpServers) else . end
      ' "$CLAUDE_MCP_CONFIG" > "$tmp"
      if ! cmp -s "$CLAUDE_MCP_CONFIG" "$tmp"; then
        mv "$tmp" "$CLAUDE_MCP_CONFIG"
        log "Removed legacy MCP server from Claude config: $CLAUDE_MCP_CONFIG"
      else
        rm -f "$tmp"
      fi
    fi

    if [ -f "$OMC_MCP_REGISTRY" ]; then
      tmp="$(mktemp)"
      jq --arg name "$LEGACY_GEMINI_MCP_NAME" 'del(.[$name])' "$OMC_MCP_REGISTRY" > "$tmp"
      if ! cmp -s "$OMC_MCP_REGISTRY" "$tmp"; then
        mv "$tmp" "$OMC_MCP_REGISTRY"
        log "Removed legacy MCP server from OMC registry: $OMC_MCP_REGISTRY"
      else
        rm -f "$tmp"
      fi
    fi

    if [ -f "$OMC_MCP_REGISTRY_STATE" ]; then
      tmp="$(mktemp)"
      jq --arg name "$LEGACY_GEMINI_MCP_NAME" '
        .managedServers = ((.managedServers // []) | map(select(. != $name)))
      ' "$OMC_MCP_REGISTRY_STATE" > "$tmp"
      if ! cmp -s "$OMC_MCP_REGISTRY_STATE" "$tmp"; then
        mv "$tmp" "$OMC_MCP_REGISTRY_STATE"
        log "Removed legacy MCP server state: $OMC_MCP_REGISTRY_STATE"
      else
        rm -f "$tmp"
      fi
    fi
  fi

  if [ -f "$CODEX_CONFIG" ]; then
    tmp="$(mktemp)"
    awk -v target="[mcp_servers.${LEGACY_GEMINI_MCP_NAME}]" '
      BEGIN { skip = 0 }
      /^\[/ {
        if ($0 == target) {
          skip = 1
          next
        }
        skip = 0
      }
      skip { next }
      { print }
    ' "$CODEX_CONFIG" > "$tmp"
    if ! cmp -s "$CODEX_CONFIG" "$tmp"; then
      mv "$tmp" "$CODEX_CONFIG"
      log "Removed legacy MCP server from Codex config: $CODEX_CONFIG"
    else
      rm -f "$tmp"
    fi
  fi
}

main() {
  require_command claude
  require_command git
  require_command npm

  ensure_dirs
  install_git_ignore
  install_omc_cli
  install_wrapper
  mirror_macos_claude_auth
  ensure_marketplace
  ensure_plugin
  run_omc_setup
  merge_safe_base_settings
  remove_legacy_gemini_image_generation
  validate_settings

  log "OMC isolated config root: $OMC_CONFIG_DIR"
  log "OMC centralized state root: $OMC_STATE_DIR"
  log "Normal Claude remains on: $HOME/.claude"
}

main "$@"
