# vim:ft=kitty

## name: Aether
## license: MIT
## source: ported from omarchy alacritty aether theme
##         (scripts-prompts-config/backups/omarchy-dotfiles-20260214-111647)

background           #0a100b
foreground           #e0e5e1
selection_background #27362f
selection_foreground #e8ede9
cursor               #8aab96
cursor_text_color    #0a100b
url_color            #9ab8ac

# Tabs
active_tab_background   #8aab96
active_tab_foreground   #0a100b
inactive_tab_background #1a241d
inactive_tab_foreground #5a7a6a

# Windows
active_border_color   #8aab96
inactive_border_color #1a241d

# normal
color0 #0a100b
color1 #c4a89a
color2 #8aab96
color3 #d4cba8
color4 #8aa8a0
color5 #b8a8a0
color6 #9ab8ac
color7 #d8ddd9

# bright
color8  #5a7a6a
color9  #d8ccc4
color10 #a3c4af
color11 #e5e0d4
color12 #b4d0c0
color13 #e0d8d2
color14 #c4dccb
color15 #e8ede9
